### ISSUE TITLE
Support configuration for UrlMatcher

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#126]
.. or we should at least document it.

**Comment by sagikazarmark** [comment]
Do you mean RequestConditional plugin and a RequestMatcher?

**Comment by Nyholm** [comment]
Yes, I've never worked with the RequestConditional plugin. We should add support for that plugin.

**Comment by sagikazarmark** [comment]
Hm, yes, it sounds like a good idea. Although we have a RequestMatcher interface, I guess most of the times we want to use the default implementation, so I suggest the following plugin configuration:

``` yaml
request_condition:
    # optional if nothing bellow is provided
    matcher: matcher.service

    # these are optional if the matcher service is provided
    # and creates an instance of the default implementation
    path: null
    host: null
    methods: []
    schemes: []
```

I don't recall how we solved multiple instance of the same plugin: by naming or passing an array to the plugin config?
