### ISSUE TITLE
Configure default plugins

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#17]
There are some plugins in `php-http/plugins` that got dependencies. We should allow the user to configure those plugins. 

```yaml
httplug: 
  plugins: 
    cache:
      service: 'acme.cache'
      config: 
        respect_headers: true
    logger:
      formatter: 'acme.formatter'
```

Reference: https://github.com/php-http/HttplugBundle/pull/16#discussion_r48946387
