### ISSUE TITLE
Error with auto discovery

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#188]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | dev-master

#### Actual Behavior
```
ServiceCircularReferenceException: Circular reference detected for service "httplug.auto_discovery.auto_discovered_client", path: "httplug.auto_discovery.auto_discovered_client".
```

#### Steps to Reproduce

```yaml
httplug:
  clients:
    curl:
      factory: 'httplug.factory.curl'
      http_methods_client: true
```

```php
HttpClientDiscovery::find();
```

#### To fix this PR

I added a failing test for this issue. Please make a PR to branch [issue-188](https://github.com/php-http/HttplugBundle/tree/issue-188)
