### ISSUE TITLE
Cannot autowire service Http\HttplugBundle\Collector\Formatter

### ISSUE THREAD

**Issue by Soullivaneuh** [php-http/HttplugBundle#210]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | v1.7.1

#### Actual Behavior

I have the following error with no-debug env:

```
  [Symfony\Component\DependencyInjection\Exception\AutowiringFailedException]                                                                                                                                                                 
  Cannot autowire service "Http\HttplugBundle\Collector\Formatter": argument "$formatter" of method "__construct()" references interface "Http\Message\Formatter" but no such service exists.                                                 
  Cannot autowire service "httplug.factory.docker": argument "$formatter" of method "Http\HttplugBundle\Collector\ProfileClientFactory::__construct()" references class "Http\HttplugBundle\Collector\Formatter" but no such service exists.  
```

#### Expected Behavior

No error and service building like it works with debug setting.

#### Steps to Reproduce

Define the following services:

```yaml
services:
  httplug.factory.docker:
    class: Http\HttplugBundle\Collector\ProfileClientFactory
    arguments:
      $factory: [ Docker\DockerClient, 'createFromEnv' ]
  Docker\Docker:
    arguments:
      $httpClient: '@httplug.client.docker'
```

And run:

```
./bin/console cache:clear --env=prod
```

#### Possible Solutions

See https://github.com/php-http/HttplugBundle/issues/210#issuecomment-334863967

**Comment by Soullivaneuh** [comment]
It seems this class is loaded only with profiling enable: https://github.com/php-http/HttplugBundle/blob/3da46d5b4e6d2438a17a059bbeaf784bda00dbff/DependencyInjection/HttplugExtension.php#L58-L59

It seems legit, but it's the only way I found to get httplug logging with this client: https://github.com/docker-php/docker-php/blob/1.24/src/DockerClient.php#L62-L94

Without having to re-define anything.

Related to: https://github.com/docker-php/docker-php/pull/257

Maybe it would be great to have a `CallbackClientFactory` for this?

**Comment by Soullivaneuh** [comment]
I finally solve my issue by creating this class:

```php
use Http\HttplugBundle\ClientFactory\ClientFactory;

/**
 * Special factory that call another factory not implementing ClientFactory.
 *
 * @author Sullivan Senechal <soullivaneuh@gmail.com>
 */
final class CallableClientFactory implements ClientFactory
{
    /**
     * @var callable
     */
    private $factory;

    /**
     * @param callable $factory
     */
    public function __construct(callable $factory)
    {
        $this->factory = $factory;
    }

    /**
     * {@inheritdoc}
     */
    public function createClient(array $config = [])
    {
        return \call_user_func($this->factory, $config);
    }
}
```

And replacing the `ProfileClientFactory` by this one:

```yaml
services:
  httplug.factory.docker:
    class: AppBundle\Httplug\ClientFactory\CallableClientFactory
    arguments:
      $factory: [ Docker\DockerClient, 'createFromEnv' ]
  Docker\Docker:
    arguments:
      $httpClient: '@httplug.client.docker'
```

If you think this is a good solution, I may write a PR for that.

**Comment by fbourigault** [comment]
All collector stuff is internal and should not be used by other libraries/bundles.

**Comment by dbu** [comment]
what exactly are you trying to achieve @Soullivaneuh ? if its about logging, the idea would be to use the logger plugin with the plugin client: http://docs.php-http.org/en/latest/plugins/logger.html

if that plugin does not work for you, we need to better understand what you want to do to figure out what the right solution is.

**Comment by Soullivaneuh** [comment]
@dbu It's about logging. My solution currently works, but it's maybe not the simplier.

I also forget my configuration file:

```yaml
httplug:
  plugins:
    logger: ~
  clients:
    default:
      factory: 'httplug.factory.guzzle6'
      plugins: ['httplug.plugin.logger']
    docker:
      factory: 'httplug.factory.docker'
      plugins: ['httplug.plugin.logger']
  profiling:
    captured_body_length: 1000
```

I have to do this because I have to use this part: https://github.com/docker-php/docker-php/blob/961e1d4f2b5d6617920babe440f585d1d517a763/src/DockerClient.php#L62-L95

Do you have a cleaner view of what I'm trying to do? Can it be done simpler?

Maybe a fix must be done on the `docker-php` library to create a proper factory.
