### ISSUE TITLE
Document how to use mock with httplug

### ISSUE THREAD

**Issue by Soullivaneuh** [php-http/HttplugBundle#212]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | N/A

Httplug has a mock client for testing: http://docs.php-http.org/en/latest/clients/mock-client.html

This is great, but it would be better to be able to replace the current client service by mocks on test environment.

I suppose it's possible, but we don't have any "official" way described on the doc.

It would be a great addition IMHO.

**Comment by Soullivaneuh** [comment]
A quick working implement:

```yaml
# config_test.yml

services:
  httplug.client.mock:
    class: Http\Mock\Client
  httplug.client.default: '@httplug.client.mock'
```

And then, the services using the default client is using the mock.

Plus, I can access the mock client to check the requests. Example on a `WebTestCase`:

```php
$client->getContainer()->get('httplug.client.mock')->getRequests()
```

This might be documented, or event better, we might propose a configuration option to replace some or all the clients by mocks.

WDYT?
