### ISSUE TITLE
Cannot define cache pool on per-client basis without configuring dummy cache plugin

### ISSUE THREAD

**Issue by ostrolucky** [php-http/HttplugBundle#244]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes

I was happy to learn I can configure cache plugins on per-client basis!
However, it makes me configure default `cache` plugin anyway. This doesn't work:

```yaml
httplug:
  clients:
    app:
      plugins:
        - cache:
          cache_pool: 'app.cache.google'

```

It will result in error: `Service "httplug.client.app.plugin.cache": Parent definition "httplug.plugin.cache" does not exist.`

Ok let's add it:
```diff
httplug:
        cache: ~
```
Doesn't work either: `The child node "cache_pool" at path "httplug.plugins.cache" must be configured.`

At this point I have to configure dummy pool
```diff
-       cache: ~
+       cache:
+         cache_pool: 'app.cache.void'
```

Only now it works. What I am asking is to not force to configure default cache plugin.
