### ISSUE TITLE
Specify client for auto discovery

### ISSUE THREAD

**Issue by antonmedv** [php-http/HttplugBundle#259]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | master

#### Actual Behavior
Use of `Default` client

#### Expected Behavior

Use of 'app' client

#### Steps to Reproduce
install httplug, configure like this:
```
httplug:
    plugins:
        redirect:
            preserve_header: true

    discovery:
        client: 'auto'

    clients:
        app:
            factory: 'httplug.factory.guzzle6'
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
            config:
                connect_timeout: 1
                timeout: 2

```

Use auto discovery. But in profiler:

![image](https://user-images.githubusercontent.com/141232/40073033-e63762b6-589f-11e8-8bcb-549130497dee.png)

And no timeout.

#### Possible Solutions
Please help.
