### ISSUE TITLE
Default config (and plugins)

### ISSUE THREAD

**Issue by Soullivaneuh** [php-http/HttplugBundle#262]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 1.10.0

#### Actual Behavior

On each client we configure, we have to define the plugins we want. In case of plugin we want everywhere, we have to repeat the configuration on each of them.

#### Expected Behavior

The idea is to allow a common client configuration to be applied on each defined client.

With that, we will be able to define common plugin setup with ease. We can also think about it for other option like `http_methods_client`.

Sample:

```yaml
httplug:
    default:
        http_methods_client: true
        plugins:
            - 'httplug.plugin.logger'
    clients:
        default:
            factory: 'httplug.factory.guzzle6'
            config:
                timeout: 5
        cacheable:
            factory: 'httplug.factory.guzzle6'
            plugins:
                - 'httplug.plugin.cache'
        dummy:
            factory: 'httplug.factory.guzzle6'
            http_methods_client: false
    profiling:
        captured_body_length: 1000
```

What do you think?

**Comment by Soullivaneuh** [comment]
Current workaround with yaml anchors:

```yaml
httplug:
    plugins:
        cache:
            # Should be the auto-wired service.
            # @see https://github.com/php-http/HttplugBundle/issues/263
            cache_pool: 'cache.app'
    clients:
        default: &default
            factory: 'httplug.factory.guzzle6'
            config: &default_config
                timeout: 15
            http_methods_client: true
            plugins:
                - 'httplug.plugin.cache'
        default_v6:
            <<: *default
            config:
                <<: *default_config
                force_ip_resolve: v6

    profiling:
        captured_body_length: 1000
```

But it's not very pretty and works only with YAML.
