### ISSUE TITLE
Mock client doesn't work

### ISSUE THREAD

**Issue by igaponov** [php-http/HttplugBundle#264]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.10.0

#### Actual Behavior

Every client is decorated with Http\Client\Common\PluginClient, but \Http\HttplugBundle\ClientFactory\MockFactory::setClient() requires exactly \Http\Mock\Client, this throws an exception 
```
TypeError : Argument 1 passed to Http\HttplugBundle\ClientFactory\MockFactory::setClient() must be an instance of Http\Mock\Client, instance of Http\Client\Common\PluginClient given, called in .../getHttplug_Factory_MockService.php
```

#### Expected Behavior

No exception should be thrown.

#### Steps to Reproduce

Just use the standard config:
```
# config_test.yml
httplug:
    clients:
        mock:
            factory: 'httplug.factory.mock'
```
and run any code that uses a client.

#### Possible Solutions

Probably don't decorate mock client at all?
