### ISSUE TITLE
QueryParams auth not supported

### ISSUE THREAD

**Issue by Soullivaneuh** [php-http/HttplugBundle#265]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.10.0

#### Actual Behavior

This configuration:

```yaml
httplug:
    plugins:
        cache:
            # Should be the auto-wired service.
            # @see https://github.com/php-http/HttplugBundle/issues/263
            cache_pool: 'cache.app'
    clients:
        pagespeed:
            factory: 'httplug.factory.guzzle6'
            config:
                timeout: 5
            http_methods_client: true
            plugins:
                -
                    authentication:
                        pagespeed:
                            type: query_params
                            key: 'test'
                - 'httplug.plugin.cache'
```

Does not work.

#### Expected Behavior

The [`QueryParams`](http://docs.php-http.org/en/latest/message/authentication.html#query-params) should be managed.
