### ISSUE TITLE
Configure client with custom class

### ISSUE THREAD

**Issue by ruudk** [php-http/HttplugBundle#285]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? |yes
| Version      | 1.13.0

We use Symfony 4 auto-wiring. To make it easier to inject the right client inside the service it would be great if I could specify the class name per httplug client.

This feature is supported by [EightPointGuzzleBundle](https://github.com/8p/EightPointsGuzzleBundle) and allows you to do something like this:

```yaml
httplug:
    clients:
        acme:
            classes:
                client: 'My\Custom\HttpClient'
```

I looked at HTTPlug and I see that it uses factories to get this done. I could of course create a factory for every single httplug client, but that feels like a lot of work.

Wondering if there is a better way? I'm willing to create a PR.
