### ISSUE TITLE
Profiler does not show stack when client name contains dots

### ISSUE THREAD

**Issue by sowbiba** [php-http/HttplugBundle#298]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.13.1

#### Actual Behavior

When the client name contains dots (example : application.ms.microservice), the profiler stack cannot be opened

#### Expected Behavior

Open Request/Response stack

#### Steps to Reproduce
```
httplug:
    plugins:
        logger:
            logger: 'logger'
            formatter: null
    clients:
        application.ms.microservice: ~
``` 

#### Possible Solutions

This issue happened because `data-toggle` contains `#httplug-application.ms.microservice-1-details`

In https://github.com/php-http/HttplugBundle/blob/master/Resources/views/script/httplug.js.twig#L7

`document.querySelectorAll(selector)` the dots are considered as class selector and the target is not found
