### ISSUE TITLE
How to disable a plugin on a specific client in a specific environment ?

### ISSUE THREAD

**Issue by shulard** [php-http/HttplugBundle#306]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 1.13.1

I have some specific dev env logging features enabled in my Symfony project (full message formatter, specific log channel). In the test environment I want to fully disable the logging.

#### Actual Behavior

When I ran the code in test, the Symfony container can't compile because of invalid logger plugin configuration.

#### Expected Behavior

Since I disable the logger plugin in the test env, why is it still trying to load it ?

#### Steps to Reproduce

Here are the Yaml files used :

```yaml
# on dev
httplug:
    plugins:
        logger:
            logger: monolog.logger.http
            formatter: http.client.full-formatter
    clients:
        dicom_query:
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
                - 'httplug.plugin.logger'
```

```yaml
# on test
httplug:
    plugins:
        logger:
            enabled: false
```

I though that disabling the plugin in test will disable the plugin for all the clients but I got an error in the container regarding the plugin configuration. Also when I dump the config for my test environment I saw that the plugin is still defined in the `dicom_query` plugin list.
