### ISSUE TITLE
provide HttpMethodsClient alias too

### ISSUE THREAD

**Issue by dbu** [php-http/HttplugBundle#308]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | HttplugBundle 1.6

#### Actual Behavior

```yaml
httplug:
    clients:
        app:
            http_methods_client: true
```

when we enable the http methods client in the configuration, the container has an alias for Http\Client\HttpClient that points to the methods client service, but it does not have an alias for Http\Client\Common\HttpMethodsClientInterface

#### Expected Behavior

Autowiring should work when i explicitly specify the methods client and not just the general HttpClient.

#### Possible Solutions

Additionally add an alias for the HttpMethodsClientInterface when that client is enabled.
