### ISSUE TITLE
[Plugin] Add configuration for VCR plugin

### ISSUE THREAD

**Issue by GaryPEGEOT** [php-http/HttplugBundle#330]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | master

#### Actual Behavior

No easy way to configure the [VCR plugin](https://github.com/php-http/vcr-plugin)

#### Expected Behavior

Same configuration pattern as the other plugins

#### Possible Solutions
Either a kind of "all-in-one" implementation:
```yaml
// config.yml
httplug:
    clients:
        acme:
            # ...
            plugins:
                # ...
                - record_and_replay: # or vcr
                    mode: record # record | replay | replay_or_record
                    recorder: filesystem # optionnal
                    naming_strategy: service_id.of.naming_strategy # optionnal

```

Or a more explicit way, ie be defining a record plugin, and a replay plugin

```yaml
// config.yml
httplug:
    clients:
        acme:
            # ...
            plugins:
                # ...
                - replay:
                    throw_on_missing: false # Default to true
                - record: ~
    plugins:
        record_and_replay: # or vcr
            recorder: filesystem # optionnal
            naming_strategy: service_id.of.naming_strategy # optionnal

```
Taking the risk that people put record before replay.

Any design preference @dbu?
