### ISSUE TITLE
Plugins are ignored (?)

### ISSUE THREAD

**Issue by RiseAndCry** [php-http/HttplugBundle#331]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no
| Version      | 1.15

#### Actual Behavior

Plugins in config are ignored.
Here's my config:
```
httplug:
    clients:
        test:
            factory: 'httplug.factory.curl'
            http_methods_client: true
            plugins:
                - add_host:
                    host: 'test'
```

When i sendRequest (via Http\Client\Curl\Client), the request is never modified by the plugin (i've also tried `header_defaults` plugin, to no avail). They're never called. 
The error i'm getting is from Curl Client - `url malformed`. Which makes sense as there is no host.

So it seems that the configuration does not work. Am i missing something or did i misconfigure it ? i did read the documentation and it seems like it should just work in this case.

#### Expected Behavior

Well, to work out of the box.

#### Steps to Reproduce

1. `composer require php-http/httplug-bundle` 
2. use the config above.
3. 
``` 
$httpClient = $this->container->get('httplug.client.test.client');
$httpClient->sendRequest($request);
(haven't tested but something like this)
```

#### Possible Solutions

If i manually create a PluginClient (with AddHostPlugin) and pass it CurlClient, then it works fine.
But that's not what i need.
