### ISSUE TITLE
The data collector does not have reset tag

### ISSUE THREAD

**Issue by lyrixx** [php-http/HttplugBundle#390]
**PHP version**: 7.4.7

**Description**
Our application made a LOT OF http call in a CLI context, and there was the following config:

```yaml
httplug:
    profiling:
        captured_body_length: ~ # Avoid truncation of body content
```

So over time, the memory consumption increase really fast

**How to reproduce**

Call some endpoint in a loop

**Possible Solution**

add the reset tag on the collector service
