### ISSUE TITLE
Add configuration for autentication

### ISSUE THREAD

**Issue by Nyholm** [php-http/HttplugBundle#42]
I would like to configure different clients with authentication. 

```yaml
httplug:
  clients:
    guzzle5:
      factory: 'httplug.factory.guzzle5'
      plugins: ['httplug.plugin.logger']
    trans_logger:
      factory: 'httplug.factory.guzzle5'
      authentication: 
        type: 'basic'
        username: 'foo'
        password: 'bar'
    microservice2:
      factory: 'httplug.factory.guzzle5'
      plugins: ['httplug.plugin.logger', 'my_cache_plugin']
      authentication: 
        type: 'wsse'
        username: 'baz'
        password: 'biz'
```

What do you think? Is this something we should support? Do you like the config example?

**Comment by sagikazarmark** [comment]
I like this idea. Especially because I think authentication providers are easy to configure (in most cases).

**Comment by joelwurtz** [comment]
Should authentication be on the plugin level (as it is itself a plugin) ?

**Comment by sagikazarmark** [comment]
I think so, since plugin client is already used.

**Comment by Nyholm** [comment]
@joelwurtz 
I guess you could also do something like this: 

```yaml
httpug:
    plugins:
        authentication:
            name: 'my_auth'
            type: 'basic'
            username: 'foo'
            password: 'bar'
    clients:
        acme:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.authentication.my_auth']
```

**Comment by sagikazarmark** [comment]
Hm. What about "positioning" the plugin? We should check if log plugin is added and add authentication after?

**Comment by Nyholm** [comment]
Yeah. I agree with the "positioning".

**Comment by dbu** [comment]
i like the plugin proposal. is this not how we already do things? order
should follow the declaration order in the config. i would not worry about
debug mode

**Comment by Nyholm** [comment]
Using the "plugin proposal" makes more sense. But I have to modify it slightly:

```yaml
httplug:
    plugins:
        authentication:
            my_auth:
              type: 'basic'
              username: 'foo'
              password: 'bar'
            other_auth:
              type: 'wsse'
              username: 'foo'
              password: 'bar'
    clients:
        acme:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.authentication.my_auth']
```
