### ISSUE TITLE
[Profiler] No captured body (Symfony Client)

### ISSUE THREAD

**Issue by KDederichs** [php-http/HttplugBundle#420]
**PHP version**: 8.1.9

**Description**
I'm trying to communicate with an API that returns XML responses and I'm noticing that the Profiler doesn't contain the response or the request body (even though it's there).

**How to reproduce**
I have my client configured this way:
```
        client_name:
            factory: 'httplug.factory.symfony'
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'                
                - add_host:
                     host: 'https://endpoint.com'
                - header_defaults:
                      headers:
                          "Content-Type": 'application/xml'
                          "Accept": 'application/xml'
```

But I noticed it also seems to happen if you just do http_methods_client: true without any other config.

**Possible Solution**
No Clue something's not capturing the response right I'd wager.

**Additional context**

Here's a screentshot with an example request to a search engine:
<img width="1057" alt="Screenshot 2022-08-12 at 11 09 40" src="https://user-images.githubusercontent.com/24696606/184323121-9a4e5008-3765-4483-af42-4a94a185a222.png">
>

Symfony version is 6.1.3
