### ISSUE TITLE
Header authentication service configuration

### ISSUE THREAD

**Issue by soullivaneuh** [php-http/HttplugBundle#437]
**Description**

The `Header` authentication service, introduced in https://github.com/php-http/message/commit/144d13ba024d0c597830636907144bc7c23f50dd, is present since v1.9.0 of its related package.

However, it is currently not possible to configure it through the bundle configuration: https://github.com/php-http/HttplugBundle/blob/57284fb032bcafc3e978a1d7e4a2b591045f7e15/src/DependencyInjection/Configuration.php#L645-L666

**Example**

```yaml
httplug:
  clients:
    sample:
      # ...
      plugins:
        - base_uri:
            uri: "%env(SAMPLE_API_URL)%"
        - authentication:
            header:
              type: header
              name: "ApiKey"
              token: "%env(SAMPLE_API_TOKEN)%"
```

**Comment by dbu** [comment]
yeah, that is missing. the place in the configuration you linked is where we should add it indeed.

and update the documentation [here](https://docs.php-http.org/en/latest/integrations/symfony-bundle.html#authentication) and [here](https://docs.php-http.org/en/latest/integrations/symfony-full-configuration.html)

for your proposed configuration format, i would make it consistent with the name in the authentication class, so it would be 

```
  - authentication:
      header:
          type: header
          name: "ApiKey"
          value: "%env(SAMPLE_API_TOKEN)%"
```

do you want to do a pull request for it?
