### ISSUE TITLE
Support multiple logger channels

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/HttplugBundle#75]
Example config with maintaining BC:

``` yaml
httplug:
    plugins:
        logger:
            logger: logger_service_id
            my_logger: ~
            my_other_logger: service_id
            my_another_logger:
                logger: ~
```

WDYT?
